directories:
  output: release
  buildResources: build
appId: com.projectmanigy.app
productName: ProjectManigy
files:
  - filter:
      - dist/**/*
      - dist-electron/**/*
      - node_modules/**/*
mac:
  category: public.app-category.productivity
win:
  target: nsis
linux:
  target: AppImage
electronVersion: 22.3.27
